name: teamfight
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - ca-certificates=2022.07.19=haa95532_0
  - certifi=2022.9.24=py39haa95532_0
  - colorama=0.4.5=py39haa95532_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - glib=2.69.1=h5dc1a3c_1
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - icu=58.2=ha925a31_3
  - intel-openmp=2022.1.0=h59b6b97_3788
  - ipykernel=6.15.2=py39haa95532_0
  - ipython=8.4.0=py39haa95532_0
  - jedi=0.18.1=py39haa95532_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_0
  - jupyter_client=7.3.5=py39haa95532_0
  - jupyter_core=4.11.1=py39haa95532_0
  - kiwisolver=1.4.2=py39hd77b12b_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=8_mkl
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=8_mkl
  - libclang=12.0.0=default_h627e005_2
  - libdeflate=1.8=h2bbff1b_5
  - libffi=3.4.2=hd77b12b_4
  - libiconv=1.16=h2bbff1b_2
  - liblapack=3.9.0=8_mkl
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.4.0=h8a3f274_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - libxgboost=1.5.0=hd77b12b_2
  - libxml2=2.9.14=h0ad7f3c_0
  - libxslt=1.1.35=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.5.2=py39haa95532_0
  - matplotlib-base=3.5.2=py39hd77b12b_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - mkl=2020.4=hb70f87d_311
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.5=py39haa95532_0
  - numpy=1.23.1=py39h1a62c8c_0
  - openssl=1.1.1q=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h2e25243_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hdc2b20a_1
  - pip=22.2.2=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.5.0=py39haa95532_2
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39haa95532_0
  - pyqt=5.15.7=py39hd77b12b_0
  - pyqt5-sip=12.11.0=py39hd77b12b_0
  - python=3.9.13=h6244533_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2022.1=py39haa95532_0
  - pywin32=302=py39h2bbff1b_2
  - pyzmq=23.2.0=py39hd77b12b_0
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_4
  - qtwebkit=5.212=h3ad3cdb_4
  - scikit-learn=1.1.2=py39hfd4428b_0
  - scipy=1.8.1=py39h5567194_2
  - setuptools=63.4.1=py39haa95532_0
  - sip=6.6.2=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py39h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - tzdata=2022c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py39haa95532_2
  - xgboost=1.5.0=py39haa95532_2
  - xz=5.2.6=h8cc25b3_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.12=h8cc25b3_3
  - zstd=1.5.2=h19a0ad4_0
prefix: C:\Users\david\anaconda3\envs\teamfight
